#-*- coding: shift-jis -*-
#:kivy 1.10.1

BoxLayout:
	orientation: 'vertical'
    Label:
        size_hint_y:None
        height: 40
        valign: 'center'
        text: '頭文字を選択してください'
    AnchorLayout:
        anchor_x:'center'
        anchor_y:'center'
        GridLayout:
            id: ic
            #orientation: 'lr-tb'
            cols: 3

            padding: 20
            spacing: 10

            size_hint: None, None
            height: self.minimum_height
            width: self.minimum_width