#-*- coding: shift-jis -*-
#:kivy 1.10.1

DataBaseScreen:
    name: 'DataBaseList'
    fullscreen: True

    BoxLayout:
        orientation:'vertical'

        padding: [0,15,0,0]
        AnchorLayout:
            id: header
            anchor_x:'center'
            anchor_y:'center'
            padding: [10,0,10,0]
            size_hint_y: None
            height: 40

            AnchorLayout:
                anchor_x:'left'
                anchor_y:'center'
                BoxLayout:
                    size_hint_x: None
                    width: self.minimum_width
                    spacing: 10
                    Button:
                        text:'新規登録'
                        size_hint_x:None
                        width: 80
                        on_release: app.open_dbc_popup(False)
                    Button:
                        text:'読み込み'
                        size_hint_x:None
                        width: 80
                        on_release: app.open_dbc_popup(True)
        
        ScrollView:
            StackLayout:
                id: db_list

                orientation: 'lr-tb'

                padding: [10, 20, 10, 0]
                spacing: 20
                
                size_hint_y: None
                height: self.minimum_height

                canvas.before:
                    Color:
                        rgba: 1, 1, 1, 1
                    Rectangle:
                        size: self.size
                        pos: self.pos
        
        BoxLayout:
            orientation:'vertical'
            size_hint_y: None
            height: 80
            spacing: 0
            padding: 10
            canvas.before:
                Color:
                    rgba: 0.128, 0.128, 0.128, 1
                Rectangle:
                    size: self.size
                    pos: self.pos

            AnchorLayout:
                id: footer
                anchor_x: 'center'
                anchor_y: 'bottom'

                    
            AnchorLayout:
                anchor_x: 'center'
                anchor_y: 'top'
                Label:
                    text: '頭文字選択'



       