#-*- coding: shift-jis -*-
#:kivy 1.10.1

DataBaseScreen:
    name: 'DataBaseList'
    fullscreen: True

    BoxLayout:
        orientation:'vertical'

        padding: [0,15,0,0]
        BoxLayout:
            id: header

            #anchor_x:'center'
            #anchor_y:'center'

            padding: [10,0,10,10]

            size_hint_y: None
            height: 50

            spacing: 5

            Button:
                text:'新規作成'
                size_hint_x:None
                width: 80
                #on_release: app.open_dbc_popup(False)
                on_release: app.open_main_popup(self, mode='create_db', load_mode=False)
            Button:
                text:'読み込み'
                size_hint_x:None
                width: 80
                #on_release: app.open_dbc_popup(True)
                on_release: app.open_main_popup(self, mode='create_db', load_mode=True)
        
        ScrollView:
            StackLayout:
                id: db_list

                orientation: 'lr-tb'

                padding: [10, 20, 10, 0]
                spacing: 20
                
                size_hint_y: None
                height: self.minimum_height

                canvas.before:
                    Color:
                        rgba: 1, 1, 1, 1
                    Rectangle:
                        size: self.size
                        pos: self.pos
        
        BoxLayout:
            orientation:'vertical'
            size_hint_y: None
            height: 80
            spacing: 0
            padding: 10
            canvas.before:
                Color:
                    rgba: 0.128, 0.128, 0.128, 1
                Rectangle:
                    size: self.size
                    pos: self.pos

            AnchorLayout:
                id: footer
                anchor_x: 'center'
                anchor_y: 'bottom'



       