#-*- coding: shift-jis -*-
#:kivy 1.10.1

DataBaseScreen:
    name: 'ThumbnailView'
    fullscreen: True

    BoxLayout:
        orientation:'vertical'

        padding: [0,15,0,0]
        AnchorLayout:
            id: header
            anchor_x:'center'
            anchor_y:'center'
            padding: [10,0,10,0]
            size_hint_y: None
            height: 40

            AnchorLayout:
                anchor_x:'left'
                anchor_y:'center'
                Label:
                    text:app.loaded_title
                    font_size: 16

            AnchorLayout:
                anchor_x:'right'
                anchor_y:'center'
                Button:
                    id: fe_btn
                    text:'解除'
                    size_hint:None, None
                    size: 80, 40
                    on_release: app.exit_filter(self)
        
        ScrollView:
            StackLayout:
                id: thumbnails

                orientation: 'lr-tb'

                padding: [10,0,10,0]
                spacing: 10
                
                size_hint_y: None
                height: self.minimum_height

        
        BoxLayout:
            orientation:'vertical'
            size_hint_y: None
            height: 70
            spacing: 0
            padding: 10
            canvas.before:
                Color:
                    rgba: 0.128, 0.128, 0.128, 1
                Rectangle:
                    size: self.size
                    pos: self.pos

            AnchorLayout:
                id: footer
                anchor_x: 'center'
                anchor_y: 'bottom'

                BoxLayout:
                    id: jump_layout
                    size_hint_x: None
                    width: 300
                    padding: 0
            
            AnchorLayout:
                anchor_x: 'center'
                anchor_y: 'top'
                Label:
                    text: '{0}-{1} of {2}'.format(app.page_range[0]+1, app.page_range[1]+1, app.view_file_num)
